"""Semantic cluster detection for SignalForge."""

from collections import defaultdict

import numpy as np

from sklearn.cluster import KMeans
from sklearn.metrics import (
    calinski_harabasz_score,
    davies_bouldin_score,
    silhouette_score,
)


# ============================================================
# CONFIGURATION
# ============================================================

N_CLUSTERS = 100
RANDOM_STATE = 42
N_INIT = 10


# ============================================================
# CLUSTERING
# ============================================================

def cluster_embeddings(
    embeddings,
    n_clusters=N_CLUSTERS,
    random_state=RANDOM_STATE,
    n_init=N_INIT,
):
    """
    Cluster normalized semantic embeddings using KMeans.

    Current SignalForge configuration:

        n_clusters=100
        random_state=42
        n_init=10

    Parameters
    ----------
    embeddings : numpy.ndarray
        Semantic embeddings generated by embeddings.py.

    n_clusters : int
        Number of semantic clusters.

    random_state : int
        Random seed for reproducibility.

    n_init : int
        Number of KMeans initializations.

    Returns
    -------
    labels : numpy.ndarray
        Cluster label assigned to each post.

    clusterer : KMeans
        Fitted KMeans model.
    """

    if embeddings is None:
        raise ValueError(
            "Embeddings cannot be None."
        )

    embeddings = np.asarray(
        embeddings
    )

    if embeddings.ndim != 2:
        raise ValueError(
            "Embeddings must be a 2-dimensional array."
        )

    if len(embeddings) == 0:
        raise ValueError(
            "No embeddings supplied for clustering."
        )

    if n_clusters <= 1:
        raise ValueError(
            "n_clusters must be greater than 1."
        )

    if n_clusters >= len(embeddings):
        raise ValueError(
            "n_clusters must be smaller than "
            "the number of posts."
        )

    print("\n")
    print("=" * 60)
    print("SEMANTIC CLUSTERING")
    print("=" * 60)

    print(
        f"\nPosts: {len(embeddings)}"
    )

    print(
        f"Embedding dimensions: "
        f"{embeddings.shape[1]}"
    )

    print(
        f"Number of clusters: "
        f"{n_clusters}"
    )

    # --------------------------------------------------------
    # KMeans
    # --------------------------------------------------------

    clusterer = KMeans(
        n_clusters=n_clusters,
        random_state=random_state,
        n_init=n_init,
    )

    labels = clusterer.fit_predict(
        embeddings
    )

    print(
        "\nKMeans clustering complete."
    )

    print(
        f"Clusters generated: "
        f"{len(np.unique(labels))}"
    )

    return labels, clusterer


# ============================================================
# GROUP CLUSTERS
# ============================================================

def group_posts_by_cluster(
    posts,
    labels,
):
    """
    Group posts by their cluster label.
    """

    if len(posts) != len(labels):
        raise ValueError(
            "Number of posts must match "
            "number of cluster labels."
        )

    clusters = defaultdict(list)

    for post, label in zip(
        posts,
        labels,
    ):
        clusters[int(label)].append(
            post
        )

    return dict(clusters)


# ============================================================
# PRINT CLUSTERS
# ============================================================

def print_clusters(
    posts,
    labels,
    max_clusters=10,
    posts_per_cluster=5,
):
    """
    Print a sample of posts from the
    largest semantic clusters.

    Unlike HDBSCAN, KMeans does not have
    a noise cluster (-1).
    """

    clusters = group_posts_by_cluster(
        posts,
        labels,
    )

    print("\n")
    print("=" * 60)
    print("SEMANTIC CLUSTERS")
    print("=" * 60)

    # --------------------------------------------------------
    # Sort clusters by size
    # --------------------------------------------------------

    sorted_clusters = sorted(
        clusters.items(),
        key=lambda item: len(
            item[1]
        ),
        reverse=True,
    )

    for cluster_no, cluster_posts in sorted_clusters[
        :max_clusters
    ]:

        print("\n" + "=" * 60)

        print(
            f"Cluster {cluster_no} "
            f"| {len(cluster_posts)} posts"
        )

        print("=" * 60)

        for post in cluster_posts[
            :posts_per_cluster
        ]:

            title = (
                post.get("title")
                or ""
            )

            content = (
                post.get("content")
                or ""
            )

            print(
                f"\nPost ID: "
                f"{post.get('post_id')}"
            )

            print(
                f"Title: {title}"
            )

            print(
                f"Content: "
                f"{content[:300]}"
            )


# ============================================================
# CLUSTER SIZE STATISTICS
# ============================================================

def calculate_cluster_sizes(
    labels,
):
    """
    Calculate the number of posts
    belonging to each cluster.
    """

    unique_labels, counts = np.unique(
        labels,
        return_counts=True,
    )

    return dict(
        zip(
            unique_labels.tolist(),
            counts.tolist(),
        )
    )


# ============================================================
# EVALUATION
# ============================================================

def evaluate_clustering(
    embeddings,
    labels,
):
    """
    Calculate internal clustering metrics.

    Metrics:

        - Silhouette Score
        - Davies-Bouldin Index
        - Calinski-Harabasz Score

    KMeans does not generate noise points,
    so all posts are included in the metrics.

    Ground-truth metrics such as ARI and NMI
    are intentionally not calculated because
    the current posts table does not contain
    a true_topic / ground-truth label.
    """

    embeddings = np.asarray(
        embeddings
    )

    labels = np.asarray(
        labels
    )

    num_posts = len(labels)

    unique_labels = np.unique(
        labels
    )

    num_clusters = len(
        unique_labels
    )

    # --------------------------------------------------------
    # Basic statistics
    # --------------------------------------------------------

    cluster_sizes = calculate_cluster_sizes(
        labels
    )

    smallest_cluster = (
        min(cluster_sizes.values())
        if cluster_sizes
        else 0
    )

    largest_cluster = (
        max(cluster_sizes.values())
        if cluster_sizes
        else 0
    )

    results = {
        "num_posts": num_posts,
        "num_clusters": num_clusters,
        "num_clustered_points": num_posts,
        "num_noise_points": 0,
        "noise_percentage": 0.0,
        "smallest_cluster": smallest_cluster,
        "largest_cluster": largest_cluster,
        "silhouette": None,
        "davies_bouldin": None,
        "calinski_harabasz": None,
    }

    # --------------------------------------------------------
    # Print statistics
    # --------------------------------------------------------

    print("\n")
    print("=" * 60)
    print("CLUSTERING STATISTICS")
    print("=" * 60)

    print(
        f"Number of posts: "
        f"{num_posts}"
    )

    print(
        f"Number of clustered posts: "
        f"{num_posts}"
    )

    print(
        f"Number of clusters: "
        f"{num_clusters}"
    )

    print(
        f"Smallest cluster: "
        f"{smallest_cluster}"
    )

    print(
        f"Largest cluster: "
        f"{largest_cluster}"
    )

    # --------------------------------------------------------
    # Internal metrics
    # --------------------------------------------------------

    if (
        num_clusters >= 2
        and num_posts > num_clusters
    ):

        results["silhouette"] = (
            silhouette_score(
                embeddings,
                labels,
            )
        )

        results["davies_bouldin"] = (
            davies_bouldin_score(
                embeddings,
                labels,
            )
        )

        results["calinski_harabasz"] = (
            calinski_harabasz_score(
                embeddings,
                labels,
            )
        )

        print("\n")
        print(
            "--- Internal Clustering Metrics ---"
        )

        print(
            f"Silhouette Score       : "
            f"{results['silhouette']:.4f}"
        )

        print(
            f"Davies-Bouldin Index   : "
            f"{results['davies_bouldin']:.4f}"
        )

        print(
            f"Calinski-Harabasz      : "
            f"{results['calinski_harabasz']:.4f}"
        )

    else:

        print(
            "\nNot enough valid clusters "
            "for internal metrics."
        )

    return results