"""Exploratory Data Analysis for SignalForge."""

import math
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


# ============================================================
# PATHS
# ============================================================

# File location:
#     Signal_Forge/
#         ml/
#             eda/
#                 eda.py
#
# parents[0] -> ml/eda
# parents[1] -> ml
# parents[2] -> project root

PROJECT_ROOT = Path(__file__).resolve().parents[2]

INPUT_FILE = PROJECT_ROOT / "outputs" / "cleaned_posts.csv"

EDA_DIR = PROJECT_ROOT / "outputs" / "eda"

SUMMARY_FILE = EDA_DIR / "summary.txt"


# ============================================================
# LOAD CLEANED DATA
# ============================================================

def load_data():
    """
    Load the cleaned posts generated by data_wrangling.py.

    This script does NOT connect to PostgreSQL.
    """

    if not INPUT_FILE.exists():
        raise FileNotFoundError(
            f"Could not find:\n"
            f"{INPUT_FILE}\n\n"
            f"Run data_wrangling.py first."
        )

    df = pd.read_csv(
        INPUT_FILE,
        encoding="utf-8",
    )

    print("=" * 70)
    print("SIGNALFORGE EXPLORATORY DATA ANALYSIS")
    print("=" * 70)

    print("\nInput file:")
    print(f"    {INPUT_FILE}")

    print(f"\nRows loaded: {len(df):,}")
    print(f"Columns:     {len(df.columns):,}")

    return df


# ============================================================
# BASIC DATASET INFORMATION
# ============================================================

def basic_information(df):

    lines = [
        "=" * 70,
        "1. BASIC DATASET INFORMATION",
        "=" * 70,
        f"Rows:     {len(df):,}",
        f"Columns:  {len(df.columns):,}",
        "",
        "Columns:",
    ]

    for column in df.columns:
        lines.append(
            f"  - {column}"
        )

    # Current ingestion output uses post_id.
    if "post_id" in df.columns:

        lines.append(
            f"\nUnique post_id values: "
            f"{df['post_id'].nunique():,}"
        )

        lines.append(
            f"Duplicate post_id rows: "
            f"{df['post_id'].duplicated().sum():,}"
        )

    # Keep support for datasets that still contain `id`.
    elif "id" in df.columns:

        lines.append(
            f"\nUnique id values: "
            f"{df['id'].nunique():,}"
        )

        lines.append(
            f"Duplicate id rows: "
            f"{df['id'].duplicated().sum():,}"
        )

    if "external_id" in df.columns:

        lines.append(
            f"Unique external_id values: "
            f"{df['external_id'].nunique():,}"
        )

        lines.append(
            f"Duplicate external_id rows: "
            f"{df['external_id'].duplicated().sum():,}"
        )

    return lines


# ============================================================
# MISSING VALUES
# ============================================================

def missing_value_analysis(df):

    lines = [
        "",
        "=" * 70,
        "2. MISSING VALUE ANALYSIS",
        "=" * 70,
    ]

    for column in df.columns:

        count = int(
            df[column].isna().sum()
        )

        percentage = (
            count / len(df) * 100
            if len(df)
            else 0
        )

        lines.append(
            f"{column:<20}"
            f"{count:>8,}"
            f"  ({percentage:>6.2f}%)"
        )

    return lines


# ============================================================
# TEXT LENGTH ANALYSIS
# ============================================================

def text_length_analysis(df):

    lines = [
        "",
        "=" * 70,
        "3. TEXT LENGTH ANALYSIS",
        "=" * 70,
    ]

    columns = [
        "title",
        "content",
        "clean_title",
        "clean_content",
        "embedding_text",
    ]

    for column in columns:

        if column not in df.columns:
            continue

        lengths = (
            df[column]
            .fillna("")
            .astype(str)
            .str.len()
        )

        lines.extend([
            "",
            column,
            f"  Minimum: {lengths.min():.0f}",
            f"  Mean:    {lengths.mean():.2f}",
            f"  Median:  {lengths.median():.0f}",
            f"  75th %:  {lengths.quantile(.75):.0f}",
            f"  90th %:  {lengths.quantile(.90):.0f}",
            f"  95th %:  {lengths.quantile(.95):.0f}",
            f"  99th %:  {lengths.quantile(.99):.0f}",
            f"  Maximum: {lengths.max():.0f}",
        ])

        for threshold in [
            10,
            20,
            50,
            100,
            200,
        ]:

            count = int(
                (lengths < threshold).sum()
            )

            percentage = (
                count / len(df) * 100
                if len(df)
                else 0
            )

            lines.append(
                f"  < {threshold:>3} chars: "
                f"{count:>7,} "
                f"({percentage:>6.2f}%)"
            )

    return lines


# ============================================================
# SCORE ANALYSIS
# ============================================================

def score_analysis(df):

    lines = [
        "",
        "=" * 70,
        "4. SCORE / ENGAGEMENT ANALYSIS",
        "=" * 70,
    ]

    if "score" not in df.columns:

        lines.append(
            "score column not found."
        )

        return lines

    scores = pd.to_numeric(
        df["score"],
        errors="coerce",
    ).fillna(0)

    lines.extend([
        f"Minimum:        {scores.min():.2f}",
        f"Mean:           {scores.mean():.2f}",
        f"Median:         {scores.median():.2f}",
        f"75th percentile: {scores.quantile(.75):.2f}",
        f"90th percentile: {scores.quantile(.90):.2f}",
        f"95th percentile: {scores.quantile(.95):.2f}",
        f"99th percentile: {scores.quantile(.99):.2f}",
        f"Maximum:         {scores.max():.2f}",
        f"Zero-score posts: "
        f"{int((scores == 0).sum()):,}",
        f"Negative-score posts: "
        f"{int((scores < 0).sum()):,}",
    ])

    return lines


# ============================================================
# TEMPORAL ANALYSIS
# ============================================================

def temporal_analysis(df):

    lines = [
        "",
        "=" * 70,
        "5. TEMPORAL ANALYSIS",
        "=" * 70,
    ]

    if "published_at" not in df.columns:

        lines.append(
            "published_at column not found."
        )

        return lines

    dates = pd.to_datetime(
        df["published_at"],
        errors="coerce",
        utc=True,
    )

    invalid = int(
        dates.isna().sum()
    )

    valid = dates.dropna()

    lines.append(
        f"Invalid/missing dates: {invalid:,}"
    )

    if valid.empty:
        return lines

    lines.append(
        f"First post: {valid.min()}"
    )

    lines.append(
        f"Last post:  {valid.max()}"
    )

    lines.append(
        f"Time span:  "
        f"{valid.max() - valid.min()}"
    )

    # --------------------------------------------------------
    # Posts by year
    # --------------------------------------------------------

    yearly = (
        valid
        .dt.year
        .value_counts()
        .sort_index()
    )

    lines.append(
        "\nPOSTS BY YEAR"
    )

    for year, count in yearly.items():

        lines.append(
            f"  {year}: {count:,}"
        )

    # --------------------------------------------------------
    # Posts by month
    # --------------------------------------------------------

    monthly = (
        valid
        .dt.to_period("M")
        .value_counts()
        .sort_index()
    )

    lines.append(
        "\nPOSTS BY MONTH"
    )

    for month, count in monthly.items():

        lines.append(
            f"  {month}: {count:,}"
        )

    # --------------------------------------------------------
    # Daily density
    # --------------------------------------------------------

    daily = (
        valid
        .dt.floor("D")
        .value_counts()
        .sort_index()
    )

    full_range = pd.date_range(
        start=valid.min().floor("D"),
        end=valid.max().floor("D"),
        freq="D",
        tz="UTC",
    )

    lines.extend([
        "",
        "DAILY DENSITY",
        f"  Calendar days:     {len(full_range):,}",
        f"  Active days:       {len(daily):,}",
        f"  Zero-post days:    "
        f"{len(full_range) - len(daily):,}",
        f"  Mean posts/day:    {daily.mean():.2f}",
        f"  Median posts/day:  {daily.median():.2f}",
        f"  Maximum posts/day: {daily.max():,}",
    ])

    return lines


# ============================================================
# COMMUNITY ANALYSIS
# ============================================================

def community_analysis(df):

    lines = [
        "",
        "=" * 70,
        "6. COMMUNITY ANALYSIS",
        "=" * 70,
    ]

    if "community_id" not in df.columns:

        lines.append(
            "community_id column not found."
        )

        return lines

    communities = (
        df["community_id"]
        .fillna("unknown")
        .astype(str)
        .value_counts()
    )

    lines.append(
        f"Unique communities: "
        f"{len(communities):,}"
    )

    lines.append(
        "\nTop 20 communities:"
    )

    for community, count in communities.head(20).items():

        lines.append(
            f"  {community}: {count:,}"
        )

    return lines


# ============================================================
# DOMAIN ANALYSIS
# ============================================================

def domain_analysis(df):

    lines = [
        "",
        "=" * 70,
        "7. DOMAIN ANALYSIS",
        "=" * 70,
    ]

    if "domain" not in df.columns:

        lines.append(
            "domain column not found."
        )

        return lines

    domains = (
        df["domain"]
        .fillna("unknown")
        .astype(str)
        .value_counts()
    )

    lines.append(
        f"Unique domains: "
        f"{len(domains):,}"
    )

    lines.append(
        "\nTop 20 domains:"
    )

    for domain, count in domains.head(20).items():

        lines.append(
            f"  {domain}: {count:,}"
        )

    return lines


# ============================================================
# DUPLICATE CONTENT
# ============================================================

def duplicate_content_analysis(df):

    lines = [
        "",
        "=" * 70,
        "8. DUPLICATE CONTENT ANALYSIS",
        "=" * 70,
    ]

    if "embedding_text" not in df.columns:

        lines.append(
            "embedding_text column not found."
        )

        return lines

    duplicate_mask = (
        df["embedding_text"]
        .fillna("")
        .duplicated(keep=False)
    )

    lines.append(
        f"Rows involved in duplicate text: "
        f"{int(duplicate_mask.sum()):,}"
    )

    lines.append(
        f"Unique duplicated text values: "
        f"{df.loc[duplicate_mask, 'embedding_text'].nunique():,}"
    )

    return lines


# ============================================================
# CLEANED TEXT SAMPLE
# ============================================================

def sample_analysis(df):

    lines = [
        "",
        "=" * 70,
        "9. CLEANED TEXT SAMPLE",
        "=" * 70,
    ]

    columns = [
        column
        for column in [
            "title",
            "content",
            "embedding_text",
        ]
        if column in df.columns
    ]

    for number, (_, row) in enumerate(
        df[columns].head(10).iterrows(),
        start=1,
    ):

        lines.append(
            f"\nPost {number}"
        )

        for column in columns:

            value = str(
                row[column]
            )

            limit = (
                350
                if column == "embedding_text"
                else 250
            )

            lines.append(
                f"  {column}: "
                f"{value[:limit]}"
            )

    return lines


# ============================================================
# CREATE PLOTS
# ============================================================

def create_plots(df):

    print("\n" + "=" * 70)
    print("GENERATING EDA PLOTS")
    print("=" * 70)

    EDA_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    # --------------------------------------------------------
    # Embedding text length
    # --------------------------------------------------------

    if "embedding_text" in df.columns:

        lengths = (
            df["embedding_text"]
            .fillna("")
            .astype(str)
            .str.len()
        )

        upper = lengths.quantile(.99)

        plt.figure(
            figsize=(10, 6)
        )

        plt.hist(
            lengths[lengths <= upper],
            bins=50,
        )

        plt.xlabel("Characters")
        plt.ylabel("Number of Posts")
        plt.title(
            "Embedding Text Length Distribution"
        )

        plt.tight_layout()

        plt.savefig(
            EDA_DIR / "text_length_distribution.png",
            dpi=150,
        )

        plt.close()

    # --------------------------------------------------------
    # Title length
    # --------------------------------------------------------

    if "title" in df.columns:

        lengths = (
            df["title"]
            .fillna("")
            .astype(str)
            .str.len()
        )

        upper = lengths.quantile(.99)

        plt.figure(
            figsize=(10, 6)
        )

        plt.hist(
            lengths[lengths <= upper],
            bins=40,
        )

        plt.xlabel("Characters")
        plt.ylabel("Number of Posts")
        plt.title(
            "Title Length Distribution"
        )

        plt.tight_layout()

        plt.savefig(
            EDA_DIR / "title_length_distribution.png",
            dpi=150,
        )

        plt.close()

    # --------------------------------------------------------
    # Content length
    # --------------------------------------------------------

    if "content" in df.columns:

        lengths = (
            df["content"]
            .fillna("")
            .astype(str)
            .str.len()
        )

        upper = lengths.quantile(.99)

        plt.figure(
            figsize=(10, 6)
        )

        plt.hist(
            lengths[lengths <= upper],
            bins=50,
        )

        plt.xlabel("Characters")
        plt.ylabel("Number of Posts")
        plt.title(
            "Content Length Distribution"
        )

        plt.tight_layout()

        plt.savefig(
            EDA_DIR / "content_length_distribution.png",
            dpi=150,
        )

        plt.close()

    # --------------------------------------------------------
    # Score
    # --------------------------------------------------------

    if "score" in df.columns:

        scores = pd.to_numeric(
            df["score"],
            errors="coerce",
        ).fillna(0)

        upper = scores.quantile(.99)

        plt.figure(
            figsize=(10, 6)
        )

        plt.hist(
            scores[scores <= upper],
            bins=50,
        )

        plt.xlabel("Score")
        plt.ylabel("Number of Posts")
        plt.title(
            "Score Distribution up to 99th Percentile"
        )

        plt.tight_layout()

        plt.savefig(
            EDA_DIR / "score_distribution.png",
            dpi=150,
        )

        plt.close()

        # ----------------------------------------------------
        # Log-transformed score
        # ----------------------------------------------------

        plt.figure(
            figsize=(10, 6)
        )

        log_scores = scores.apply(
            lambda x: math.copysign(
                math.log10(abs(x) + 1),
                x,
            )
        )

        plt.hist(
            log_scores,
            bins=50,
        )

        plt.xlabel(
            "Signed log10(|score| + 1)"
        )

        plt.ylabel(
            "Number of Posts"
        )

        plt.title(
            "Log-Transformed Score Distribution"
        )

        plt.tight_layout()

        plt.savefig(
            EDA_DIR / "log_score_distribution.png",
            dpi=150,
        )

        plt.close()

    # --------------------------------------------------------
    # Posts by year / month / day
    # --------------------------------------------------------

    if "published_at" in df.columns:

        dates = pd.to_datetime(
            df["published_at"],
            errors="coerce",
            utc=True,
        ).dropna()

        if not dates.empty:

            # ------------------------------------------------
            # Posts by year
            # ------------------------------------------------

            yearly = (
                dates
                .dt.year
                .value_counts()
                .sort_index()
            )

            plt.figure(
                figsize=(12, 6)
            )

            plt.bar(
                yearly.index.astype(str),
                yearly.values,
            )

            plt.xlabel("Year")
            plt.ylabel("Number of Posts")
            plt.title("Posts by Year")
            plt.xticks(rotation=45)

            plt.tight_layout()

            plt.savefig(
                EDA_DIR / "posts_by_year.png",
                dpi=150,
            )

            plt.close()

            # ------------------------------------------------
            # Posts by month
            # ------------------------------------------------

            monthly = (
                dates
                .dt.to_period("M")
                .value_counts()
                .sort_index()
            )

            plt.figure(
                figsize=(14, 6)
            )

            plt.plot(
                monthly.index.astype(str),
                monthly.values,
            )

            plt.xlabel("Month")
            plt.ylabel("Number of Posts")
            plt.title("Posts by Month")

            step = max(
                1,
                len(monthly) // 15,
            )

            plt.xticks(
                range(
                    0,
                    len(monthly),
                    step,
                ),
                monthly.index.astype(str)[::step],
                rotation=45,
            )

            plt.tight_layout()

            plt.savefig(
                EDA_DIR / "posts_by_month.png",
                dpi=150,
            )

            plt.close()

            # ------------------------------------------------
            # Posts by day
            # ------------------------------------------------

            daily = (
                dates
                .dt.floor("D")
                .value_counts()
                .sort_index()
            )

            plt.figure(
                figsize=(14, 6)
            )

            plt.plot(
                daily.index,
                daily.values,
            )

            plt.xlabel("Date")
            plt.ylabel("Number of Posts")
            plt.title("Daily Post Volume")

            plt.tight_layout()

            plt.savefig(
                EDA_DIR / "posts_by_day.png",
                dpi=150,
            )

            plt.close()

    # --------------------------------------------------------
    # Domains
    # --------------------------------------------------------

    if "domain" in df.columns:

        domains = (
            df["domain"]
            .fillna("unknown")
            .astype(str)
            .value_counts()
            .head(15)
            .sort_values()
        )

        plt.figure(
            figsize=(10, 7)
        )

        plt.barh(
            domains.index,
            domains.values,
        )

        plt.xlabel("Number of Posts")
        plt.ylabel("Domain")
        plt.title("Top 15 Domains")

        plt.tight_layout()

        plt.savefig(
            EDA_DIR / "top_domains.png",
            dpi=150,
        )

        plt.close()

    # --------------------------------------------------------
    # Communities
    # --------------------------------------------------------

    if "community_id" in df.columns:

        communities = (
            df["community_id"]
            .fillna("unknown")
            .astype(str)
            .value_counts()
            .head(15)
            .sort_values()
        )

        plt.figure(
            figsize=(10, 7)
        )

        plt.barh(
            communities.index,
            communities.values,
        )

        plt.xlabel("Number of Posts")
        plt.ylabel("Community ID")
        plt.title("Top 15 Communities")

        plt.tight_layout()

        plt.savefig(
            EDA_DIR / "top_communities.png",
            dpi=150,
        )

        plt.close()

    print(
        f"Plots saved to:\n"
        f"    {EDA_DIR}"
    )


# ============================================================
# MAIN
# ============================================================

def main():

    df = load_data()

    lines = []

    lines.extend(
        basic_information(df)
    )

    lines.extend(
        missing_value_analysis(df)
    )

    lines.extend(
        text_length_analysis(df)
    )

    lines.extend(
        score_analysis(df)
    )

    lines.extend(
        temporal_analysis(df)
    )

    lines.extend(
        community_analysis(df)
    )

    lines.extend(
        domain_analysis(df)
    )

    lines.extend(
        duplicate_content_analysis(df)
    )

    lines.extend(
        sample_analysis(df)
    )

    report = "\n".join(lines)

    print("\n")
    print(report)

    EDA_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    SUMMARY_FILE.write_text(
        report,
        encoding="utf-8",
    )

    create_plots(df)

    print("\n" + "=" * 70)
    print("EDA COMPLETE")
    print("=" * 70)

    print(
        f"\nSummary:"
        f"\n    {SUMMARY_FILE}"
    )

    print(
        f"\nPlots:"
        f"\n    {EDA_DIR}"
    )


if __name__ == "__main__":
    main()